# Generated by Django 3.2.9 on 2022-05-04 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20220501_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', through='news.UserCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
